name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    name: Maven Compile
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Compile Application
        run: |
          mvn clean compile
  test:
    name: Maven Test
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run Maven Tests
        run: |
          mvn test


  security-scan:
    name: Trivy Security Scan
    needs: compile
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Resolve Maven Dependencies
        run: |
          mvn dependency:resolve
          mvn dependency:go-offline

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
            | gpg --dearmor \
            | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" \
            | sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Trivy Filesystem Scan
        run: |
          trivy fs \
            --scanners vuln \
            --format table \
            -o fs-report.txt \
            .

      - name: Gitleaks Installation  
        run: sudo apt install gitleaks -y 

      - name: Gitleaks Code Scan
        run: gitleaks detect source -r gitleaks-reports.json -f json

 
    
   
 

    
